// Mocks generated by Mockito 5.4.6 from annotations
// in grapql_users_app/test/features/users/data/repositories/user_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:grapql_users_app/features/users/data/datasources/user_remote_data_source.dart'
    as _i2;
import 'package:grapql_users_app/features/users/data/models/user_model.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUsersResponse_0 extends _i1.SmartFake implements _i2.UsersResponse {
  _FakeUsersResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserModel_1 extends _i1.SmartFake implements _i3.UserModel {
  _FakeUserModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRemoteDataSource extends _i1.Mock
    implements _i2.UserRemoteDataSource {
  MockUserRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UsersResponse> getUsers({
    required int? page,
    required int? limit,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUsers, [], {
              #page: page,
              #limit: limit,
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i4.Future<_i2.UsersResponse>.value(
              _FakeUsersResponse_0(
                this,
                Invocation.method(#getUsers, [], {
                  #page: page,
                  #limit: limit,
                  #forceRefresh: forceRefresh,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.UsersResponse>);

  @override
  _i4.Future<_i3.UserModel> getUserById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getUserById, [id]),
            returnValue: _i4.Future<_i3.UserModel>.value(
              _FakeUserModel_1(this, Invocation.method(#getUserById, [id])),
            ),
          )
          as _i4.Future<_i3.UserModel>);

  @override
  _i4.Future<_i3.UserModel> createUser({
    required String? name,
    required String? username,
    required String? email,
    required String? phone,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [], {
              #name: name,
              #username: username,
              #email: email,
              #phone: phone,
            }),
            returnValue: _i4.Future<_i3.UserModel>.value(
              _FakeUserModel_1(
                this,
                Invocation.method(#createUser, [], {
                  #name: name,
                  #username: username,
                  #email: email,
                  #phone: phone,
                }),
              ),
            ),
          )
          as _i4.Future<_i3.UserModel>);
}
